#!/bin/bash
# Copyright (C) 2024 Gridware GmbH
# Startup script for OCS worker nodes

set -e

echo "=================================================="
echo "OCS Worker Node Startup: $(hostname)"
echo "=================================================="

# Fix ownership of bind-mounted home dir for gridware (uid 1000).
# Required on Linux hosts where bind mounts retain host UIDs; on macOS
# Docker Desktop maps UIDs transparently and this is a no-op.
chown -R gridware:gridware /home/gridware

# The bind mount hides the .bashrc that the image put into /home/gridware, so
# write it again here (the master does the same; whoever comes first wins).
if ! grep -q "/etc/profile.d/ocs.sh" /home/gridware/.bashrc 2>/dev/null; then
    cat /etc/ocs-bashrc.snippet >> /home/gridware/.bashrc
fi
chown gridware:gridware /home/gridware/.bashrc

# Configure /etc/hosts with all cluster nodes
echo "Configuring /etc/hosts with cluster nodes..."
cat >> /etc/hosts << EOF
10.100.0.10 ocs-master
10.100.0.11 ocs-worker1
10.100.0.12 ocs-worker2
EOF

# Display configured hosts
echo "Cluster nodes configured:"
grep "^10.100.0" /etc/hosts

# Start SSH daemon. The gridware SSH keypair is generated by the master
# and shared via the common /home/gridware mount, so nothing else is
# needed here for passwordless SSH between the nodes.
echo "Starting SSH daemon..."
ssh-keygen -A
if ! pgrep -x sshd > /dev/null; then
    /usr/sbin/sshd
fi

# Wait for master node to complete installation
echo "Waiting for master node to complete OCS installation..."
MAX_WAIT=300
ELAPSED=0
while [ ! -f "/opt/ocs/default/common/settings.sh" ] && [ $ELAPSED -lt $MAX_WAIT ]; do
    sleep 5
    ELAPSED=$((ELAPSED + 5))
    echo "Waiting for master installation... (${ELAPSED}s/${MAX_WAIT}s)"
done

if [ ! -f "/opt/ocs/default/common/settings.sh" ]; then
    echo "ERROR: Master installation did not complete within ${MAX_WAIT} seconds"
    exit 1
fi

echo "Master installation detected. Configuring worker node..."

# Accept newer Linux kernels in the arch detection script of an existing
# installation. Upstream only whitelists kernels up to 6.*; newer kernels
# (e.g. 7.x used by OrbStack) are reported as UNSUPPORTED-* and daemon
# startup fails with "can't determine path to Cluster Scheduler utility
# binaries". Idempotent: the pattern no longer matches once replaced.
if [ -f /opt/ocs/util/arch ]; then
    sed -i 's/2\.4\.\*|2\.6\.\*|3\.\*|4\.\*|5\.\*|6\.\*)/2.4.*|2.6.*|[3-9].*)/' /opt/ocs/util/arch
fi

# Source OCS environment
. /opt/ocs/default/common/settings.sh

# Wait a bit more for master daemons to be fully ready
echo "Waiting for master daemons to be ready..."
sleep 10

# Start execd daemon on this worker (skip if already running)
if pgrep -x sge_execd > /dev/null; then
    echo "execd daemon is already running."
else
    echo "Starting execd daemon on $(hostname)..."
    /opt/ocs/default/common/sgeexecd start
fi

# Wait to ensure execd is running
sleep 3

# Verify execd started
if pgrep -x sge_execd > /dev/null; then
    echo "Execd daemon started successfully"
else
    echo "WARNING: Execd daemon may not have started correctly"
fi

# Join the @allhosts host group, which is what creates the all.q instance on
# this node. The master installs its own execd only (installing ours remotely
# would require passwordless root ssh), so the node has to register itself.
# A running execd alone just makes the node show up in qhost - without a queue
# instance nothing can be scheduled here, and a job bound to this node, e.g.
# "qrsh -l h=$(hostname)", fails with "could not be scheduled, try again later".
# Idempotent: an already registered host is left untouched, including its slot
# count, so restarts never overwrite a slot number set by an administrator.
echo "Registering $(hostname) in the @allhosts host group..."
REGISTERED=false
for attempt in 1 2 3 4 5 6 7 8 9 10; do
    if qconf -shgrp_resolved @allhosts 2>/dev/null | tr -d '\\' | tr ' ' '\n' |
            grep -qx "$(hostname)"; then
        echo "$(hostname) is a member of @allhosts."
        REGISTERED=true
        break
    fi

    if qconf -aattr hostgroup hostlist "$(hostname)" @allhosts; then
        # A fresh queue instance inherits the default slot count of all.q,
        # which is 1. Give it the cores of this node, like the installer does.
        qconf -mattr queue slots "$(nproc)" "all.q@$(hostname)" ||
            echo "WARNING: cannot set slot count of all.q@$(hostname)"
        REGISTERED=true
        break
    fi

    echo "qmaster not ready yet, retrying registration (${attempt}/10)..."
    sleep 5
done

if [ "$REGISTERED" != "true" ]; then
    echo "WARNING: $(hostname) is not in @allhosts, it has no queue instance"
    echo "         and cannot run jobs. Check the qmaster and retry with:"
    echo "         qconf -aattr hostgroup hostlist $(hostname) @allhosts"
fi

echo "=================================================="
echo "Worker node $(hostname) ready and joined cluster."
echo "=================================================="

# Execute the command passed to the container
exec "$@"
